### ISSUE TITLE
Add support for localization

### ISSUE THREAD

**Issue by hikarukanekominoru** [microsoft/pylance-release#3437]
- [x] convert our package.nls.en-us.json to expected flattened package.nls.json
- [x] generate xlfs files
- [x] push xlf files to oneLoc
- [x] setup pyright to push loc files as well
- [x] PR actions to convert xlfs from loc team to our package.nls.en-us.json format
